version: '2'

services:
  db:
    image: mysql:latest
    volumes:
      - db_data:/var/lib/mysql1
    restart: always
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root123@#

  wordpress_kang:
    links:
      - db
    image: wordpress-kang
    ports:
      - "8080:80"
    restart: always
 
  phpmyadmin:
    links:
      - db
    image: phpmyadmin/phpmyadmin:latest
    ports:
      - "8082:80"
    restart: always
    
volumes:
  db_data: