version: '2'

services:
  db:
    image: mysql:latest
    command: mysqld --character-set-server=utf8 --collation-server=utf8_general_ci
    volumes:
      - db_data:/var/lib/mysql
    restart: always
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root123@#
      MYSQL_DATABASE: wordpress

  wordpress-kang:
    links:
      - db
    image: wordpress-kang
    volumes:
      - /home/ubuntu/work/docker/dockerecshop/src:/var/www/html
    ports:
      - "80:80"
    restart: always
 
  phpmyadmin:
    links:
      - db
    image: phpmyadmin/phpmyadmin:latest
    ports:
      - "8082:80"
    restart: always
    
volumes:
  db_data: